name: E2E Tests

on:
  pull_request:
    branches: [master]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          npm ci

      - name: Build Next app
        run: npm run build

      - name: Start Next & run tests
        run: |
          nohup npm start &
          sleep 5
          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" \
            npx playwright test --headed
